apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wordpress.fullname" . }}
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/wordpress
