apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql.fullname" . }}

spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.storageClass }}
  hostPath:
    path: /var/wordpress
