apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
{{ include "mysql.labels" . | indent 4 }} 
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi


